const TO_PRODUCTS_BY_SELECTED_CATEGORY = 1;
const TO_PRODUCT_TYPE = 2;
const TO_ADD_PRODUCT = 3;
const TO_CART = 4;
const TO_EMPTY_CART = 5;
const TO_MY_ORDERS = 6;
const TO_MY_ORDER = 7;
const TO_CONFIRM_ORDER = 8;
const TO_DELETE_ITEM = 9;

export default {
    TO_PRODUCTS_BY_SELECTED_CATEGORY,
    TO_PRODUCT_TYPE,
    TO_ADD_PRODUCT,
    TO_CART,
    TO_EMPTY_CART,
    TO_MY_ORDERS,
    TO_MY_ORDER,
    TO_CONFIRM_ORDER,
    TO_DELETE_ITEM
}