const STATUS_CREATE = "CREATE";
const STATUS_PENDING = "PENDIENTE";
const STATUS_CONFIRMED = "CONFIRMADO";
const STATUS_PREPARING= "PREPARANDO";
const STATUS_FINISHED = "FINALIZADO";
const STATUS_DELIVERED = "ENTREGADO";
const STATUS_REJECTED = "RECHAZADO";
const STATUS_CANCELED = "CANCELADO";

export default{
    STATUS_CREATE,
    STATUS_PENDING,
    STATUS_CONFIRMED,
    STATUS_PREPARING,
    STATUS_FINISHED,
    STATUS_DELIVERED,
    STATUS_REJECTED,
    STATUS_CANCELED
}